[tool.flask-livetw]
flask_root = "src"
static_folder = "app/static"
templates_folder = "app/templates"
templates_glob = "**/*.html"
base_layout = "layout.html"
livetw_folder = ".dev"
flask_app = "src/app"
